import type { Metadata } from "next";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import AuthProvider from "@/lib/AuthProvider";
import Navbar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "ECO ROUTE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <Navbar />
          {/* Add ml-20 to shift the content right by the width of the collapsed navbar */}
          <main className="ml-20">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
